#find the difference
"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

"""


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s_set = set(s)
        t_set = set(t)
        print(s_set)
        print(t_set)
        diff = ''.join(s_set.symmetric_difference(t_set))
        return diff

      
    




s1 = Solution()

#check examples

print(s1.findTheDifference("abcd","abcde"))

print(s1.findTheDifference("","y"))

print(s1.findTheDifference("aa","aea"))

print(s1.findTheDifference("toto","toto"))

print(s1.findTheDifference("a","aa"))

